### PR TITLE
Fix for resolving modules relative to cwd on Windows

### LINKED ISSUE #106: node-resolve will incorrectly resolve modules from cwd on Windows
This is caused by the parsing regex in node-module-paths.js and some odd Windows behaviour. Here's a repro setup and trace:

At the start, cwd is E:\kettle, which contains a module infusion at E:\kettle\node_modules\infusion. It has made a call

```
resolve.sync("infusion", {basedir: "E:\"})
```

which should NOT resolve.

Unfortunately, https://github.com/substack/node-resolve/blob/master/lib/node-modules-paths.js#L22 has split the path "E:\" to the two segments [ "E:", "" ]

This then gets processed by the main loop in node-module-paths https://github.com/substack/node-resolve/blob/master/lib/node-modules-paths.js#L27 to the following array: [ "E:node_modules", "E:\node_modules"]. YOU WOULD THINK that the two elements of this array harmlessly refer to the same path, but they do not. On Windows, there is the somewhat insane convention that a bare drive letter in fact refers to the CWD _for that drive_ which in this case is E:\kettle. Therefore the first element of this array incorrectly resolves into "E:\kettle\node_modules\infusion" by the time it reaches the LoadAsDirectorySync algorithm.

It seems that there is already some special-casing for the win32 platform in node-module-paths.js , but sadly we need a bit more. Fixing the splitRe on this line https://github.com/substack/node-resolve/blob/master/lib/node-modules-paths.js#L20 to make sure that it does not split on :\ should be enough.

Note that since JavaScript regexes don't support zero-width lookbehind, my pull uses a clunky scheme for fusing the first two path segments back together again if we detect that the path begins with a drive letter.

### PR DESCRIPTION
**Pull request by amb26**
Resolves #106, #52, #96 - even includes a test case!

### CODE REVIEW

**Comment by amb26** [comment]
The build fails because Travis CI is bound to node 0.8 and some ancient and broken edition of npm

**Comment by ljharb** [comment]
Rather than adding a custom matcher, we should be using `path` module methods to concatenate and normalize paths, as opposed to manually concatenating and hardcoding separators.

If you'd like to rebase this, and use that approach, that'd be great!

**Comment by ljharb** [comment]
I've tweaked and tested `node-modules-paths` in #113, and they now pass in Windows.

Would you mind taking a look and making sure i've covered your drive letter cases as well?

**Comment by amb26** [comment]
Thanks @ljharb - I've checked over the solution in #113 and it works for me - thanks for the fix. Looking forward to the release - cheers!

**Pull request closed without merging**
