### PR TITLE
[fixes #79] resolve.sync should re-throw non ENOENT errors

### LINKED ISSUE #79: sync should rethrow if stat throws (but not ENOENT)
https://github.com/substack/node-resolve/blob/1.1.6/lib/sync.js#L9-L11

It is possible for `fs.statSync` to fail do for reasons other then ENOENT. As such, we should re-throw or we end up with an un-related error do  to the stat object being missing: https://github.com/substack/node-resolve/blob/1.1.6/lib/sync.js#L1

note this would also fix the a-symmetry with async – which correctly handles the error https://github.com/substack/node-resolve/blob/1.1.6/lib/async.js#L23

an example would be: `fs.statSync('\\\\some-unc-path\\folder name\\missing file')` will throw unfortunately throw an `UnknownError` :(

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by stefanpenner** [comment]
I'm unclear what the travis failure is, feels CI caching or npm related?

**Comment by ljharb** [comment]
@stefanpenner would you mind rebasing this and rerunning tests? (or checking the "allow maintainers to edit" checkbox)

**Comment by stefanpenner** [comment]
Maintainers can now edit :)

**Comment by stefanpenner** [comment]
@ljharb thanks for handling this! I was on my phone at the time, and couldn't take care of it myself, you rock!

**Pull request merged**
