### PR TITLE
add searched extensions to errors

### PR DESCRIPTION
**Pull request by wenzowski**
as requested in #45

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks - I'd have really preferred modifying the previous PR instead of opening a new one tho :-/

**Comment by wenzowski** [comment]
> would you mind rebasing, and checking the "allow edits" box?

would usually have rebased and force pushed but didn't know there was a way to "allow edits" except by opening a new PR

**Comment by ljharb** [comment]
No worries - there's a checkbox on all PRs you've made, on the right side.

**Comment by ljharb** [comment]
Sadly I ended up having to revert this; it caused #119. I'll re-revert it later in v2.0.0.

**Pull request merged**
