### PR TITLE
readme: update API docs link for require.resolve()

### PR DESCRIPTION
**Pull request by paulirish**

### CODE REVIEW

**Comment by steelbrain** [comment]
Ping @substack

**Comment by ljharb** [comment]
@paulirish would you mind rebasing this and rerunning tests? (or checking the "allow maintainers to edit" checkbox)

**Comment by paulirish** [comment]
rebased. it's just the readme so i doubt tests will be affected.

**Comment by ljharb** [comment]
pretty unlikely :-) i just prefer having tests passing on all PRs, even docs ones. Thanks!

**Pull request merged**
