### PR TITLE
Attempts to find package.json data for deep references for #62

### PR DESCRIPTION
**Pull request by justinbmeyer**
This is for #62.  The basics work.  It only changes the behavior when a resolve looks like:

```js
resolve("foo/bar");
```

I did not implement this for sync.  I'm hoping to get some feedback first.  Let me know what you think.  Thanks!

### CODE REVIEW

**Comment by justinbmeyer** [comment]
@substack @defunctzombie Any thoughts?

**Comment by substack** [comment]
Merged into 1.1.0 for now. I changed the indexing to use arrays instead of strings since otherwise paths like `aaanode_moduleszzz` would match.

**Comment by substack** [comment]
Can you also send a patch for the docs to describe how opts.pathFilter works?

**Comment by justinbmeyer** [comment]
Woohoo!  Yep, I will get this to you Thursday.  Thanks!

**Comment by justinbmeyer** [comment]
@substack Sorry about taking so long.  The readme docs are spartan, so I'm not sure how much detail you want in the docs.  Some options:

## Spartan

* opts.pathFinder - transform a path within a package. 

## Minimal

* opts.pathFinder(pkg, path, relativePath) - transform a path within a package. 

## Args and return value

* opts.pathFinder(pkg, path, relativePath) - transform a path within a package. 
  * pkg - package data
  * path - the path being resolved
  * relativePath - the path relative from the package.json location.
  * returns - a relative path that will be joined from the package.json location.
  

Let me know what you think. Thanks!

**Comment by substack** [comment]
args and return value is nice and thorough

**Pull request closed without merging**
