### PR TITLE
stack trace should show searched extensions

### PR DESCRIPTION
**Pull request by wenzowski**
traces can be a little cryptic when we don't know what kinds of files `resolve` is searching for

### CODE REVIEW

**Comment by wenzowski** [comment]
@substack rebased on master

**Comment by ljharb** [comment]
@wenzowski the list of extensions is either being explicitly passed by the user, or it's the same list that all versions of node use - `.js`, `.json`, and `.node` (altho this library currently only uses the first, but will soon be all three). Can you explain the use case here where you *wouldn't* know which extensions are being searched?

**Comment by wenzowski** [comment]
> this library only uses the first
Nailed it right there?

This is a pretty old PR. I think the Derby use case was passing a custom list. Just because the user is passing a list doesn't mean the list is stored in code: could be in ENV. I thought knowing was helpful at the time, so I changed it.

**Comment by ljharb** [comment]
@wenzowski makes sense. would you mind rebasing, and checking the "allow edits" box? I think this is a useful PR.

**Comment by wenzowski** [comment]
oh, "Allow edits from maintainers." is in the right hand column after sending, silly me

**Pull request closed without merging**
