### PR TITLE
add preserveSymlinks option

### PR DESCRIPTION
**Pull request by zkochan**
Ref #130

### CODE REVIEW

**Comment by zkochan** [comment]
It doesn't seem like my changes have caused the CI fails on old Node versions

**Comment by zkochan** [comment]
Now it works on Windows but the package I use to create the symlink (for testing) doesn't work on old Node versions...

**Comment by zkochan** [comment]
@ljharb could you please review this?

although Travis is failing on some node versions, it doesn't seem to be caused by these changes.

**Comment by zkochan** [comment]
Thanks! 

> but perhaps we shouldn't make this be a breaking change by enabling the behavior by default?

I think `preserveSymlinks` should be `false` by default because that is how Node resolution works by default. If you think this is dangerous or it is preferable to not make breaking changes (I know that this package is very widely used), I am fine we making it `true` now and then maybe in the future we'll make it `false` by default

**Comment by ljharb** [comment]
Yeah - let's do that (have it default to true for now) and release a semver-minor.

I'll plan a breaking change in the future that flips it to `false` - if you'd like to make that PR after this one's merged, I'll rebase and merge it when it's time :-)

**Comment by zkochan** [comment]
OK cool, I'll push the change in a few minutes

**Comment by zkochan** [comment]
Changed `preserveSymlinks` to true by default

Added a notice to README about changing the default value of `preserveSymlinks` in next major version. It will help me convince users of `resolve` change the value of `preserveSymlinks` earlier.

**Pull request merged**
